### ISSUE TITLE
How increase directions coordinate limit ?

### ISSUE THREAD

**Issue by samatzp** [stafyniaksacha/mapbox-api#5]
as I understand now we can only send 3 coordinate

needed for  drawing route 100+ waypoints

**Comment by stafyniaksacha** [comment]
The direction API can handle up to 25 waypoints: 
https://docs.mapbox.com/api/navigation/directions/

| coordinates | number | A semicolon-separated list of between two and 25 {longitude},{latitude} coordinate pairs to visit in order. |
|-- | -- | --|
